name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - pyspark=3.1.2
  - pyarrow=1.0.0
  - pandas=0.25.3
  - lightgbm=3.2.1
  - scikit-learn=0.24.2
  - hyperopt=0.2.5
  - category_encoders=2.2.2
  - numpy=1.19.5
  - requests=2.24.0
  - tqdm=4.51.0
  - retrying=1.3.3
  - timeout-decorator=0.5.0
  - python-dateutil=2.8.2
  - pydantic=1.8.2
  - mypy=0.790
  - flake8=3.8.4
