name: Evaluate Spark predictive testing model

on:
  pull_request:
    branches:
      - master
    paths:
      - bin/train-ptesting-model.py
      - models/spark/logs/*
      - models/spark/indexes/latest
  issue_comment:
    types: [created, edited]
jobs:
  eval-spark-model:
    if: ${{ github.event_name == 'pull_request' ||
      (contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/eval')) }}
    runs-on: ubuntu-latest
    env:
      python: 3.6
    strategy:
      fail-fast: true
    steps:
      - name: Checkout predictive-testing repository
        uses: actions/checkout@v2
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Install Python packages (Python ${{ env.python }})
        run: python -m pip install -r ./bin/requirements.txt
      - name: Install JavaScript packages
        run: npm install fs
      - name: Build predictive model and compute eval metrics
        run: ./bin/train-spark-model.sh
      - name: Post the result metrics
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs')
            const metrics = fs.readFileSync('models/spark/model-eval-metric-summary.md').toString('utf8')
            const commentBody = `Result Metrics:\n${metrics}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
      - name: Upload updated model as artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: spark-model-metrics
          path: |
            models/spark/model.pkl
            models/spark/model-eval-*
            models/spark/failed-tests.json
