name: Evaluate Spark predictive testing model

on:
  pull_request:
    branches:
      - master
    paths:
      - bin/train-ptesting-model.py
      - models/spark/logs/github-logs.json
jobs:
  eval-spark-model:
    runs-on: ubuntu-latest
    env:
      python: 3.6
    strategy:
      fail-fast: true
    steps:
      - name: Checkout predictive-testing repository
        uses: actions/checkout@v2
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Install Python packages (Python ${{ env.python }})
        run: python -m pip install -r ./bin/requirements.txt
      - name: Build predictive model and compute eval metrics
        run: ./bin/train-spark-model.sh
      - name: Post the result metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          curl -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d "{\"body\": \"$(cat models/spark/model-eval-metric-summary.md)\"}" \
            ${URL}
